steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/sit737-23t1-manivannan-0f81f95/my-webapp:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "gcr.io/sit737-23t1-manivannan-0f81f95/my-webapp:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["config", "set", "compute/zone", "australia-southeast1"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["container", "clusters", "get-credentials", "hello-cluster"]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/my-webapp",
        "my-webapp=gcr.io/sit737-23t1-manivannan-0f81f95/my-webapp:$COMMIT_SHA",
      ]
images:
  - "gcr.io/sit737-23t1-manivannan-0f81f95/my-webapp:$COMMIT_SHA"
